// default package
// Generated Nov 21, 2015 11:37:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Long usId;
	private String usUserName;
	private String usPassword;
	private String usIsActive;

	public User() {
	}

	public User(String usUserName, String usPassword, String usIsActive) {
		this.usUserName = usUserName;
		this.usPassword = usPassword;
		this.usIsActive = usIsActive;
	}

	public Long getUsId() {
		return this.usId;
	}

	public void setUsId(Long usId) {
		this.usId = usId;
	}

	public String getUsUserName() {
		return this.usUserName;
	}

	public void setUsUserName(String usUserName) {
		this.usUserName = usUserName;
	}

	public String getUsPassword() {
		return this.usPassword;
	}

	public void setUsPassword(String usPassword) {
		this.usPassword = usPassword;
	}

	public String getUsIsActive() {
		return this.usIsActive;
	}

	public void setUsIsActive(String usIsActive) {
		this.usIsActive = usIsActive;
	}

}
